services:
  - type: web
    name: buscador-medico
    env: docker
    dockerfilePath: ./Dockerfile
    branch: master
    envVars:
      - key: PUBMED_API_KEY
        value: 2f850568e99e0a6f818fb945bc1ebbaec309
      - key: SEMANTIC_SCHOLAR_KEY
        value: s2k-IMjhX49IIelIRp3nP0z3zsnG5BANIoZ3pXeaYKhP
      - key: SPRINGER_NATURE_KEY
        value: 07d4526079fd4d4387a238f8511ab233
      - key: CORE_API_KEY
        value: ""
